import asyncio
import json
import os
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field
from models.agent import Classifier, Processor, Replicator, Tool
from src.message import Message, Messages
from src.agent import Agent
from src.llm import LLM, LlmApi
from src.instructions import LlmInstructions
import logging
import numpy as np
from rich import print
logging.getLogger("LiteLLM").setLevel(logging.CRITICAL)

class TopicGeneratorOutput(Replicator):
    topic: str = Field(
        description='Topic generated by the AI.'
    )

class TopicGeneratorProcessor(Processor):
    def process(self, agent: Agent, messages: list[Messages], llm: dict) -> dict | None:
        print(llm)
        return llm

def topic_generator_fn(name: str):
    return Agent(
        name=name,
        role='user:linked',
        output_schema=TopicGeneratorOutput,
        llm=LLM(
            model=LlmApi(model_name='gpt-4o-mini'),#, base_url='http://localhost:1234/v1'),
            instructions=LlmInstructions(
                background='You are a conversational topic question generator AI. Based on a given topic, your task is to create a realistic and relatable scenario that could happen in everyday life. Then, based on that scenario, write one informal, open-ended question that could naturally appear in a casual conversation.',
                tools=[],
                reasoning=False,
                steps=[
                    'Be specific in your scenario, grounding it in real-life situations (e.g., events, places, online interactions, work, school, etc.).',
                    'Keep the question simple and conversational — it should invite a short, thoughtful response (1–3 sentences).',
                    'Make sure the question is open-ended (not yes/no) and encourages some personal opinion or experience.'
                ],
                output_schema=TopicGeneratorOutput
            ),
            debug=False
        ),
        processor=TopicGeneratorProcessor(),
        num_workers=1,
    )