import asyncio
import json
import os
import random
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field
from models.agent import Classifier, Processor, Replicator, Tool
from src.message import Message, Messages
from src.agent import Agent
from src.llm import LLM, LlmApi
from src.instructions import LlmInstructions
import logging
import numpy as np
from rich import print

logging.getLogger("LiteLLM").setLevel(logging.CRITICAL)

class TopicChoiceOutput(Replicator):
    topic: str = Field(
        description='Topic generated by the AI.'
    )

class TopicChoiceProcessor(Processor):
    def process(self, agent: Agent, messages: list[Messages], llm: dict) -> dict | None:
        topic = random.choice([
            # 'technology',
            'science',
            'history',
            'art',
            'literature',
            'economy',
            'politics',
            'geography',
            'culture',
            'sports',
            'entertainment',
            'music',
            'fashion',
            'food',
            'travel',
            'business',
        ])
        return {
            'topic': topic,
        }

def topic_choice_fn(name: str):
    return Agent(
        name=name,
        role='user',
        output_schema=TopicChoiceOutput,
        llm=None,
        processor=TopicChoiceProcessor(),
        num_workers=1,
    )
