import asyncio
import json
import os
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field
from models.agent import Classifier, Processor, Replicator, Tool
from src.message import Message, Messages
from src.agent import Agent
from src.llm import LLM, LlmApi
from src.instructions import LlmInstructions
import logging
import numpy as np
from rich import print

logging.getLogger("LiteLLM").setLevel(logging.CRITICAL)

class UserInputOutput(Replicator):
    topic: str = Field(
        description='Topic generated by the AI.'
    )
    user_input: str = Field(
        description='User input.'
    )

class UserInputProcessor(Processor):
    def process(self, agent: Agent, messages: list[Messages], llm: dict) -> dict | None:
        # print(messages)
        return {
            'topic': messages[0].data[0].content['topic'],
            'user_input': input('User input: ')
        }

def user_input_fn(name: str):
    return Agent(
        name=name,
        role='user',
        output_schema=UserInputOutput,
        llm=None,
        processor=UserInputProcessor(),
        num_workers=1,
    )
